name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: HeroTest.testDamage20
      id: herotest-testdamage20
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeroTest.testDamage20
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testDamage20"
        timeout: 10
        max-score: 3
    - name: HeroTest.testPrint
      id: herotest-testprint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeroTest.testPrint
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testPrint"
        timeout: 10
        max-score: 4
    - name: MatangoTest.testDamage20
      id: matangotest-testdamage20
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: MatangoTest.testDamage20
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "MatangoTest.testDamage20"
        timeout: 10
        max-score: 3
    - name: MatangoTest.testPrint
      id: matangotest-testprint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: MatangoTest.testPrint
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "MatangoTest.testPrint"
        timeout: 10
        max-score: 4
    - name: testMain
      id: testmain
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testMain
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog81Test.testHelloWorld"
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HEROTEST-TESTDAMAGE20_RESULTS: "${{steps.herotest-testdamage20.outputs.result}}"
        HEROTEST-TESTPRINT_RESULTS: "${{steps.herotest-testprint.outputs.result}}"
        MATANGOTEST-TESTDAMAGE20_RESULTS: "${{steps.matangotest-testdamage20.outputs.result}}"
        MATANGOTEST-TESTPRINT_RESULTS: "${{steps.matangotest-testprint.outputs.result}}"
        TESTMAIN_RESULTS: "${{steps.testmain.outputs.result}}"
      with:
        runners: herotest-testdamage20,herotest-testprint,matangotest-testdamage20,matangotest-testprint,testmain
